# Generated by Django 3.2.6 on 2021-11-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='text_result',
            field=models.BooleanField(default=False),
        ),
    ]
