# Generated by Django 3.2.6 on 2021-12-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211215_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='post',
            new_name='user',
        ),
    ]
